---

- name: Clear the old website
  file:
    path: /var/www/html
    state: absent

- name: Remove previous archive
  file:
    path: /opt/www.tgz
    state: absent

- name: Archive existing build
  archive:
    path: /opt/git/ijtaba.me.uk/html
    dest: /opt/www.tgz
    exclude_path:
      - "**/.git/**"
      - "**/.git*/**"


  connection: local
  run_once: true

- name: Ensure target directory exists
  file: 
    path: /var/www/
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rwx,o=rx


- name: Copy over and extract the new website archive
  unarchive:
    src: /opt/www.tgz
    dest: /var/www/
    mode: u=rwx,g=rwx,o=rx
    owner: www-data
    group: www-data
