---
- name: Reset VM
  include: burn.yml
  tags: burn

- name: webserver
  include: webserver.yml
  tags: webserver

- name: deploy
  include: deploy.yml
  tags: deploy

- name: ssl
  include: ssl.yml
  tags: ssl
  when:
    - inventory_hostname != "localhost"
