---
- name: Install apt helper tools
  apt:
    name: software-properties-common
    state: latest

- name: Add SSL Dependent Repositories
  command: add-apt-repository "{{ item }}"
  with_items:
    - "universe"

- name: Install Let's Encrypt CertBot
  apt:
    pkg:
    - certbot
    - python3-certbot-apache
    state: present
    update_cache: yes

- name: Concatenate the SSL Domains as a single variable
  set_fact:
    all_ssl_domains: "{{ ssl_domains | join(',') }}"

- name: Configure certbot - Initial Certificate
  command: certbot --apache -n --agree-tos --redirect --uir --hsts --staple-ocsp --must-staple --email "{{ email }}" --keep-until-expiring --expand --domains "{{ all_ssl_domains }}"

- name: Ensure that certbot renew is turned on
  systemd: 
    name: certbot.timer
    state: started
    enabled: yes

